#!/usr/bin/env python3
"""Generate index.html with i18n support and version placeholders"""

import json

# Translations for UN 6 official languages
i18n = {
    "en": {
        "title": "Ship CLIs, Not Configs",
        "subtitle": "One-click offline installer for AI coding tools",
        "download_macos": "Download for macOS",
        "download_windows": "Download for Windows",
        "terminal_comment_1": "# Download, double-click, install. That's it.",
        "terminal_comment_2": "# Select: Claude Code, Codex, Gemini CLI, Kimi, Lark",
        "terminal_comment_3": "# Click: Install Now",
        "terminal_comment_4": "# Done. No npm, no Node.js, no PATH hell.",
        "stats_title_1": "AI CLIs Bundled",
        "stats_title_2": "Config Files",
        "stats_title_3": "Offline",
        "stats_title_4": "Click",
        "features_title": "Built for developers who ship",
        "feature_1_title": "Zero Config",
        "feature_1_desc": "No npm install. No PATH exports. No version conflicts. Just download, double-click, and all CLIs are ready in your terminal.",
        "feature_2_title": "100% Offline",
        "feature_2_desc": "Bundled mode packs Node.js runtime + every CLI tarball + binaries into a single executable. Install on air-gapped machines, no network required.",
        "feature_3_title": "Auto-Update",
        "feature_3_desc": "Latest mode fetches newest releases from npm and GitHub at install time. Or use the bundled payload — rebuilt daily by CI.",
        "feature_4_title": "Claude API Relay",
        "feature_4_desc": "Fill in your custom Base URL + Token in the GUI. Only affects the claude command, leaves other CLIs and system env untouched.",
        "feature_5_title": "Multilingual UI",
        "feature_5_desc": "6 UN official languages: English, Chinese, French, Spanish, Russian, Arabic. Auto-detects your system locale.",
        "feature_6_title": "Daily CI Builds",
        "feature_6_desc": "GitHub Actions checks npm and GitHub Releases every 24 hours. New CLI version? Installer rebuilds, repacks, and publishes automatically.",
        "tools_title": "5 AI CLIs, one installer",
        "claude_desc": "Anthropic's official CLI for Claude. Talk to Claude straight from your terminal.",
        "codex_desc": "OpenAI's coding assistant. Generate code, debug, refactor, all in your shell.",
        "gemini_desc": "Google's Gemini models in your terminal. Multimodal AI at your fingertips.",
        "kimi_desc": "Moonshot AI's coding CLI. Long-context reasoning for complex codebases.",
        "lark_desc": "Feishu/Lark official CLI. Automate workflows, integrations, and more.",
    },
    "zh": {
        "title": "一键安装 AI CLI,告别配置地狱",
        "subtitle": "离线打包 5 款 AI 编程工具,零配置直接用",
        "download_macos": "macOS 下载",
        "download_windows": "Windows 下载",
        "terminal_comment_1": "# 下载、双击、安装,就这么简单",
        "terminal_comment_2": "# 勾选: Claude Code, Codex, Gemini CLI, Kimi, Lark",
        "terminal_comment_3": "# 点击: 立即安装",
        "terminal_comment_4": "# 完成. 无需 npm, 无需 Node.js, 无需配置 PATH",
        "stats_title_1": "AI CLI 工具",
        "stats_title_2": "配置文件",
        "stats_title_3": "离线安装",
        "stats_title_4": "点击安装",
        "features_title": "为专注交付的开发者打造",
        "feature_1_title": "零配置",
        "feature_1_desc": "无需 npm install,无需配置 PATH,无需处理版本冲突。下载、双击,所有 CLI 即可在终端使用。",
        "feature_2_title": "100% 离线",
        "feature_2_desc": "Bundled 模式把 Node.js 运行时、所有 CLI 的 tarball、二进制文件打包进单个可执行文件。内网机器也能安装,无需联网。",
        "feature_3_title": "自动更新",
        "feature_3_desc": "Latest 模式在安装时从 npm 和 GitHub 拉取最新版本。也可使用离线包——CI 每天自动重构建。",
        "feature_4_title": "Claude API 中转",
        "feature_4_desc": "在 GUI 里填写自定义 Base URL 和 Token,只对 claude 命令生效,不影响其他 CLI 和系统环境变量。",
        "feature_5_title": "多语言界面",
        "feature_5_desc": "支持联合国 6 种官方语言:英语、中文、法语、西班牙语、俄语、阿拉伯语。自动检测系统语言。",
        "feature_6_title": "每日 CI 构建",
        "feature_6_desc": "GitHub Actions 每 24 小时检查 npm 和 GitHub Releases。发现新版本后自动重新打包并发布。",
        "tools_title": "5 款 AI CLI,一个安装器",
        "claude_desc": "Anthropic 官方 Claude CLI,在终端直接对话 Claude。",
        "codex_desc": "OpenAI 编程助手,在 shell 里生成代码、调试、重构。",
        "gemini_desc": "Google Gemini 模型终端版,多模态 AI 触手可及。",
        "kimi_desc": "月之暗面 Kimi 编程 CLI,长上下文推理处理复杂代码库。",
        "lark_desc": "飞书官方 CLI,自动化工作流和集成。",
    },
    "fr": {
        "title": "Déployez des CLIs, pas des configs",
        "subtitle": "Installateur hors ligne en un clic pour les outils de codage IA",
        "download_macos": "Télécharger pour macOS",
        "download_windows": "Télécharger pour Windows",
        "terminal_comment_1": "# Télécharger, double-cliquer, installer. C'est tout.",
        "terminal_comment_2": "# Sélectionner: Claude Code, Codex, Gemini CLI, Kimi, Lark",
        "terminal_comment_3": "# Cliquer: Installer maintenant",
        "terminal_comment_4": "# Terminé. Pas de npm, pas de Node.js, pas d'enfer PATH.",
        "stats_title_1": "CLIs IA inclus",
        "stats_title_2": "Fichiers de config",
        "stats_title_3": "Hors ligne",
        "stats_title_4": "Clic",
        "features_title": "Conçu pour les développeurs qui livrent",
        "feature_1_title": "Zéro Config",
        "feature_1_desc": "Pas de npm install. Pas d'exports PATH. Pas de conflits de version. Juste télécharger, double-cliquer, et tous les CLIs sont prêts.",
        "feature_2_title": "100% Hors ligne",
        "feature_2_desc": "Le mode Bundled intègre Node.js + chaque tarball CLI + binaires dans un exécutable unique. Installation sur machines isolées, aucun réseau requis.",
        "feature_3_title": "Mise à jour auto",
        "feature_3_desc": "Le mode Latest récupère les dernières versions depuis npm et GitHub lors de l'installation. Ou utilisez le payload embarqué — reconstruit quotidiennement par CI.",
        "feature_4_title": "Relais API Claude",
        "feature_4_desc": "Remplissez votre Base URL + Token personnalisés dans l'interface. N'affecte que la commande claude, laisse les autres CLIs et l'env système intacts.",
        "feature_5_title": "Interface multilingue",
        "feature_5_desc": "6 langues officielles de l'ONU: anglais, chinois, français, espagnol, russe, arabe. Détection automatique de la locale système.",
        "feature_6_title": "Builds CI quotidiens",
        "feature_6_desc": "GitHub Actions vérifie npm et GitHub Releases toutes les 24h. Nouvelle version CLI? L'installateur se reconstruit, republie automatiquement.",
        "tools_title": "5 CLIs IA, un installateur",
        "claude_desc": "CLI officiel Anthropic pour Claude. Parlez à Claude directement depuis votre terminal.",
        "codex_desc": "Assistant de codage OpenAI. Générez du code, déboguez, refactorisez, tout dans votre shell.",
        "gemini_desc": "Les modèles Gemini de Google dans votre terminal. IA multimodale à portée de main.",
        "kimi_desc": "CLI de codage Moonshot AI. Raisonnement à contexte long pour codebases complexes.",
        "lark_desc": "CLI officiel Feishu/Lark. Automatisez workflows, intégrations, et plus.",
    },
    "es": {
        "title": "Envía CLIs, no configs",
        "subtitle": "Instalador sin conexión de un clic para herramientas de codificación IA",
        "download_macos": "Descargar para macOS",
        "download_windows": "Descargar para Windows",
        "terminal_comment_1": "# Descargar, doble clic, instalar. Eso es todo.",
        "terminal_comment_2": "# Seleccionar: Claude Code, Codex, Gemini CLI, Kimi, Lark",
        "terminal_comment_3": "# Clic: Instalar ahora",
        "terminal_comment_4": "# Listo. Sin npm, sin Node.js, sin infierno de PATH.",
        "stats_title_1": "CLIs IA incluidos",
        "stats_title_2": "Archivos de config",
        "stats_title_3": "Sin conexión",
        "stats_title_4": "Clic",
        "features_title": "Construido para desarrolladores que entregan",
        "feature_1_title": "Cero Config",
        "feature_1_desc": "Sin npm install. Sin exports de PATH. Sin conflictos de versión. Solo descargar, doble clic, y todos los CLIs están listos.",
        "feature_2_title": "100% Sin conexión",
        "feature_2_desc": "El modo Bundled empaqueta Node.js + cada tarball CLI + binarios en un ejecutable único. Instalación en máquinas aisladas, sin red requerida.",
        "feature_3_title": "Auto-actualización",
        "feature_3_desc": "El modo Latest obtiene las últimas versiones desde npm y GitHub al instalar. O usa el payload empaquetado — reconstruido diariamente por CI.",
        "feature_4_title": "Relevo API Claude",
        "feature_4_desc": "Rellena tu Base URL + Token personalizados en la interfaz. Solo afecta el comando claude, deja otros CLIs y env del sistema intactos.",
        "feature_5_title": "Interfaz multilingüe",
        "feature_5_desc": "6 idiomas oficiales de la ONU: inglés, chino, francés, español, ruso, árabe. Detección automática de la configuración regional del sistema.",
        "feature_6_title": "Builds CI diarios",
        "feature_6_desc": "GitHub Actions verifica npm y GitHub Releases cada 24h. ¿Nueva versión CLI? El instalador se reconstruye, republica automáticamente.",
        "tools_title": "5 CLIs IA, un instalador",
        "claude_desc": "CLI oficial de Anthropic para Claude. Habla con Claude directo desde tu terminal.",
        "codex_desc": "Asistente de codificación OpenAI. Genera código, depura, refactoriza, todo en tu shell.",
        "gemini_desc": "Los modelos Gemini de Google en tu terminal. IA multimodal al alcance de la mano.",
        "kimi_desc": "CLI de codificación Moonshot AI. Razonamiento de contexto largo para bases de código complejas.",
        "lark_desc": "CLI oficial Feishu/Lark. Automatiza flujos de trabajo, integraciones y más.",
    },
    "ru": {
        "title": "Доставляйте CLI, а не конфиги",
        "subtitle": "Оффлайн-установщик одним кликом для ИИ-инструментов кодирования",
        "download_macos": "Скачать для macOS",
        "download_windows": "Скачать для Windows",
        "terminal_comment_1": "# Скачать, двойной клик, установить. Вот и всё.",
        "terminal_comment_2": "# Выбрать: Claude Code, Codex, Gemini CLI, Kimi, Lark",
        "terminal_comment_3": "# Клик: Установить сейчас",
        "terminal_comment_4": "# Готово. Никакого npm, никакого Node.js, никакого ада PATH.",
        "stats_title_1": "ИИ CLI в комплекте",
        "stats_title_2": "Файлов конфигурации",
        "stats_title_3": "Оффлайн",
        "stats_title_4": "Клик",
        "features_title": "Создано для разработчиков, которые доставляют",
        "feature_1_title": "Ноль конфигурации",
        "feature_1_desc": "Никакого npm install. Никаких экспортов PATH. Никаких конфликтов версий. Просто скачайте, дважды кликните, и все CLI готовы.",
        "feature_2_title": "100% Оффлайн",
        "feature_2_desc": "Режим Bundled упаковывает Node.js + каждый tarball CLI + бинарники в один исполняемый файл. Установка на изолированных машинах, сеть не требуется.",
        "feature_3_title": "Авто-обновление",
        "feature_3_desc": "Режим Latest получает новейшие версии из npm и GitHub при установке. Или используйте встроенный payload — перестраивается ежедневно CI.",
        "feature_4_title": "Релей Claude API",
        "feature_4_desc": "Заполните свой Base URL + Token в интерфейсе. Влияет только на команду claude, оставляет другие CLI и системную среду нетронутыми.",
        "feature_5_title": "Многоязычный интерфейс",
        "feature_5_desc": "6 официальных языков ООН: английский, китайский, французский, испанский, русский, арабский. Автоопределение системной локали.",
        "feature_6_title": "Ежедневные сборки CI",
        "feature_6_desc": "GitHub Actions проверяет npm и GitHub Releases каждые 24ч. Новая версия CLI? Установщик пересобирается, переиздаётся автоматически.",
        "tools_title": "5 ИИ CLI, один установщик",
        "claude_desc": "Официальный CLI Anthropic для Claude. Общайтесь с Claude прямо из терминала.",
        "codex_desc": "Помощник кодирования OpenAI. Генерируйте код, отлаживайте, рефакторите, всё в вашем shell.",
        "gemini_desc": "Модели Gemini от Google в вашем терминале. Мультимодальный ИИ под рукой.",
        "kimi_desc": "CLI кодирования Moonshot AI. Длинноконтекстное рассуждение для сложных кодовых баз.",
        "lark_desc": "Официальный CLI Feishu/Lark. Автоматизируйте рабочие процессы, интеграции и многое другое.",
    },
    "ar": {
        "title": "شحن CLIs، وليس التكوينات",
        "subtitle": "مثبت دون اتصال بنقرة واحدة لأدوات الترميز بالذكاء الاصطناعي",
        "download_macos": "تنزيل لنظام macOS",
        "download_windows": "تنزيل لنظام Windows",
        "terminal_comment_1": "# تنزيل، نقرة مزدوجة، تثبيت. هذا كل شيء.",
        "terminal_comment_2": "# اختيار: Claude Code, Codex, Gemini CLI, Kimi, Lark",
        "terminal_comment_3": "# نقر: التثبيت الآن",
        "terminal_comment_4": "# تم. لا npm، لا Node.js، لا جحيم PATH.",
        "stats_title_1": "CLIs الذكاء الاصطناعي المجمعة",
        "stats_title_2": "ملفات التكوين",
        "stats_title_3": "دون اتصال",
        "stats_title_4": "نقرة",
        "features_title": "مصمم للمطورين الذين يشحنون",
        "feature_1_title": "صفر تكوين",
        "feature_1_desc": "لا npm install. لا تصدير PATH. لا تضارب في الإصدارات. فقط تنزيل، نقرة مزدوجة، وجميع CLIs جاهزة.",
        "feature_2_title": "100٪ دون اتصال",
        "feature_2_desc": "يحزم وضع Bundled وقت تشغيل Node.js + كل tarball CLI + ثنائيات في ملف تنفيذي واحد. التثبيت على أجهزة معزولة، لا حاجة للشبكة.",
        "feature_3_title": "التحديث التلقائي",
        "feature_3_desc": "يجلب وضع Latest أحدث الإصدارات من npm و GitHub عند التثبيت. أو استخدم الحمولة المجمعة — يعاد بناؤها يوميًا بواسطة CI.",
        "feature_4_title": "ترحيل Claude API",
        "feature_4_desc": "املأ Base URL + Token المخصصين في الواجهة. يؤثر فقط على أمر claude، يترك CLIs الأخرى وبيئة النظام دون تغيير.",
        "feature_5_title": "واجهة متعددة اللغات",
        "feature_5_desc": "6 لغات رسمية للأمم المتحدة: الإنجليزية، الصينية، الفرنسية، الإسبانية، الروسية، العربية. اكتشاف تلقائي للمحلية النظام.",
        "feature_6_title": "بناء CI يومي",
        "feature_6_desc": "تحقق GitHub Actions من npm و GitHub Releases كل 24 ساعة. إصدار CLI جديد؟ المثبت يعيد البناء، يعيد النشر تلقائيًا.",
        "tools_title": "5 CLIs ذكاء اصطناعي، مثبت واحد",
        "claude_desc": "CLI الرسمي لـ Anthropic لـ Claude. تحدث إلى Claude مباشرة من محطتك الطرفية.",
        "codex_desc": "مساعد الترميز OpenAI. توليد الكود، التصحيح، إعادة الهيكلة، كل شيء في shell الخاص بك.",
        "gemini_desc": "نماذج Gemini من Google في محطتك الطرفية. ذكاء اصطناعي متعدد الوسائط في متناول يدك.",
        "kimi_desc": "CLI ترميز Moonshot AI. استدلال سياق طويل للقواعد الشيفرية المعقدة.",
        "lark_desc": "CLI الرسمي لـ Feishu/Lark. أتمتة سير العمل، التكاملات، والمزيد.",
    }
}

# Write translations to JSON file for JS to load
with open("C:/Users/zhichao5.chen/Downloads/easy-ai-cli-installer/i18n.json", "w", encoding="utf-8") as f:
    json.dump(i18n, f, ensure_ascii=False, indent=2)

print("Generated i18n.json")
print("Now update index.html to:")
print("1. Add version comment markers for sed")
print("2. Load i18n.json and switch languages with JS")
